import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Header from "@/Header";
import Footer from "@/Footer";

// font config
const lato = Lato({
  subsets: ["latin"],
  weight: ["400", "700"], // jitne weight chahiye add kar do
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* 👇 yahan font apply ho gaya puri body par */}
      <body className={`${lato.className} antialiased`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
